/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Smoke-test entry point. Returns a static string so Phase 3(d)'s parity script
 * can confirm the binding loaded.
 */
export declare function ping(): string
export interface VerifyCanonicalHashRequest {
  canonicalJsonInput: string
  expectedIntentFullHash: string
}
export interface VerifyCanonicalHashResult {
  matches: boolean
  actual: string
}
export declare function verifyCanonicalHash(req: VerifyCanonicalHashRequest): VerifyCanonicalHashResult
export interface CanonicalizeDecimalRequest {
  input: string
}
export interface CanonicalizeDecimalResult {
  canonical: string
}
export declare function canonicalizeDecimal(req: CanonicalizeDecimalRequest): CanonicalizeDecimalResult
export declare class TradingGit {
  /** Create a new TradingGit with default stub config (hash_version=2). */
  static create(): TradingGit
  /** Restore from a previously exported state JSON string. */
  static restore(stateJson: string): TradingGit
  /**
   * Stage an operation. operation_json is JSON of the Operation (serde_json
   * tagged enum). Returns JSON of AddResult.
   */
  add(operationJson: string): string
  /** Prepare a commit. Returns JSON of CommitPrepareResult. */
  commit(message: string): string
  /**
   * Execute staged operations.
   *
   * stub_results_json: optional JSON array of OperationResult to use as
   * scripted responses. When provided, they are loaded into the shared
   * buffer and consumed in order by the execute_operation closure.
   * An empty array (or None) causes the closure to use a default stub.
   *
   * Returns JSON of PushResult.
   */
  push(stubResultsJson?: string | undefined | null): string
  /** Reject the pending commit. Returns JSON of RejectResult. */
  reject(reason?: string | undefined | null): string
  /** Export the current state as JSON string (GitExportState). */
  exportState(): string
  /** Show a commit by hash. Returns JSON of GitCommit or null. */
  show(hash: string): string | null
  /** Get current status as JSON string (GitStatus). */
  status(): string
  /** Get canonical JSON of the export state (pretty=true matches TS canonicalJson). */
  canonicalExportState(): string
}
