/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TradingCoreConfig {
  dataRoot: string
  /** Per-UTA event channel capacity. Default: 1024. */
  eventQueueCapacity?: number
  /** Consecutive panic threshold before UTA is permanently disabled. Default: 5. */
  panicDisableThreshold?: number
}
export interface AccountConfig {
  id: string
  /** 'alpaca' | 'ibkr' | 'ccxt' | 'mock' */
  accountType: string
  /** 'mock-paper' for Phase 4f */
  brokerId: string
  enabled: boolean
  guards: Array<GuardConfig>
  brokerConfig: BrokerConfigPayload
}
export interface GuardConfig {
  guardType: string
  /** Serialized JSON object — opaque to napi. */
  configJson: string
}
export interface BrokerConfigPayload {
  /** Serialized JSON — opaque to napi. */
  configJson: string
}
/**
 * Per-UTA event emitted to the TypeScript host via ThreadsafeFunction.
 *
 * `seq` is u32 (not u64) so that napi-rs v2 maps it to a JS `number` rather
 * than a `BigInt`. At the trading event rate, u32 provides ~4 billion events
 * per UTA — decades of headroom. The TS side gap-detects by comparing
 * `event.seq !== lastSeq + 1` which works cleanly with plain numbers.
 */
export interface TradingCoreEvent {
  utaId: string
  /** Per-UTA monotonic counter. u32 → JS number (napi-rs v2). */
  seq: number
  /**
   * Milliseconds since Unix epoch as f64. napi-rs v2 maps i64 to JS BigInt,
   * which breaks TS `number` consumers; f64 maps to JS `number` and safely
   * represents all timestamps well past year 2100 (2^53 ms ≈ 285616 years).
   */
  timestampMs: number
  /** 'commit.notify' | 'reject.notify' | 'account.health' */
  eventType: string
  /** Serialized payload — TS parses based on event_type. */
  payloadJson: string
}
/**
 * Parameters for `stage_place_order`. All broker-shape fields are opaque JSON
 * strings; the Rust layer deserializes them back to `serde_json::Value` before
 * constructing the `Operation`.
 */
export interface StagePlaceOrderParams {
  /** JSON-serialized contract object (broker-shape passthrough). */
  contractJson: string
  /** JSON-serialized order object (broker-shape passthrough). */
  orderJson: string
  /** Optional JSON-serialized TpSl params. `None` means no take-profit/stop-loss. */
  tpslJson?: string
}
/** Parameters for `stage_modify_order`. */
export interface StageModifyOrderParams {
  orderId: string
  /** JSON-serialized changes object (broker-shape passthrough). */
  changesJson: string
}
/** Parameters for `stage_close_position`. */
export interface StageClosePositionParams {
  /** JSON-serialized contract object (broker-shape passthrough). */
  contractJson: string
  /** Optional partial-close quantity as a decimal string. */
  quantity?: string
}
/**
 * Parameters for `sync`. `current_state_json` is a JSON-serialized `GitState`.
 * `updates` is a list of order status updates.
 */
export interface OrderStatusUpdateNapi {
  orderId: string
  symbol: string
  previousStatus: string
  currentStatus: string
  filledPrice?: string
  filledQty?: string
}
/** Mirror of `crate::types::AddResult`. */
export interface AddResultNapi {
  staged: boolean
  /** Zero-based index of the operation in the staging area. */
  index: number
  /** JSON-serialized `Operation` (tagged enum — TS parses by `action` field). */
  operationJson: string
}
/** Mirror of `crate::types::CommitPrepareResult`. */
export interface CommitPrepareResultNapi {
  prepared: boolean
  hash: string
  message: string
  operationCount: number
}
/**
 * Thin mirror of a single `OperationResult` for use inside `PushResultNapi`.
 * `execution` and `order_state` are opaque JSON strings.
 */
export interface OperationResultNapi {
  action: string
  success: boolean
  orderId?: string
  /** OperationStatus as a string ('submitted' | 'filled' | 'rejected' | 'cancelled' | 'user-rejected'). */
  status: string
  /** JSON-serialized execution object, or `null`. */
  executionJson?: string
  /** JSON-serialized order_state object, or `null`. */
  orderStateJson?: string
  filledQty?: string
  filledPrice?: string
  error?: string
}
/** Mirror of `crate::types::PushResult`. */
export interface PushResultNapi {
  hash: string
  message: string
  operationCount: number
  submitted: Array<OperationResultNapi>
  rejected: Array<OperationResultNapi>
}
/** Mirror of `crate::types::RejectResult`. */
export interface RejectResultNapi {
  hash: string
  message: string
  operationCount: number
}
/**
 * Mirror of `crate::types::SyncResult` (without the `Vec<OrderStatusUpdate>`
 * to avoid exposing the canonical type directly through napi).
 */
export interface SyncResultNapi {
  hash: string
  updatedCount: number
}
/**
 * Mirror of `crate::types::GitExportState` — the full state as JSON strings.
 * `commits_json` is a JSON array of `GitCommit` objects.
 */
export interface GitExportStateNapi {
  /** JSON-serialized array of `GitCommit` objects. */
  commitsJson: string
  head?: string
}
/** Mirror of `crate::brokers::types::BrokerHealthInfo`. */
export interface BrokerHealthInfoNapi {
  /** 'healthy' | 'unhealthy' | 'offline' */
  status: string
  lastCheck: string
  message?: string
  /** u32 → JS number (napi-rs v2). */
  consecutiveFailures?: number
}
/**
 * Account snapshot derived from the latest commit's `state_after` in `GitExportState`.
 * All decimal fields are strings (precision-safe passthrough).
 *
 * Phase 4f: derived from `export_state()` — no UtaCommand extensions needed.
 */
export interface AccountSnapshotNapi {
  netLiquidation: string
  totalCashValue: string
  unrealizedPnL: string
  realizedPnL: string
}
/**
 * A single position from the latest commit's `state_after.positions`.
 *
 * `position_json` is the broker-shape position object serialized to a JSON string.
 * This matches `GitState.positions: Vec<Value>` — the shape is broker-specific and
 * is passed through opaquely to the TS host.
 */
export interface PositionSnapshotNapi {
  /** Serialized broker-shape position object. */
  positionJson: string
}
/**
 * Smoke-test entry point. Returns a static string so Phase 3(d)'s parity script
 * can confirm the binding loaded.
 */
export declare function ping(): string
export interface VerifyCanonicalHashRequest {
  canonicalJsonInput: string
  expectedIntentFullHash: string
}
export interface VerifyCanonicalHashResult {
  matches: boolean
  actual: string
}
export declare function verifyCanonicalHash(req: VerifyCanonicalHashRequest): VerifyCanonicalHashResult
export interface CanonicalizeDecimalRequest {
  input: string
}
export interface CanonicalizeDecimalResult {
  canonical: string
}
export declare function canonicalizeDecimal(req: CanonicalizeDecimalRequest): CanonicalizeDecimalResult
/**
 * Root napi object. A single `TradingCore` instance is created by Node.js and
 * holds the per-UTA actor registry. All async operations run on the Tokio
 * runtime that was active at `create()` time (Node's tokio runtime via
 * `napi-rs` `tokio_rt` feature).
 */
export declare class TradingCore {
  /**
   * Stage a place-order operation for the given UTA.
   *
   * `params.contract_json` and `params.order_json` are JSON-serialized
   * broker-shape objects (opaque to napi; deserialized inside this method).
   */
  stagePlaceOrder(utaId: string, params: StagePlaceOrderParams): Promise<AddResultNapi>
  /**
   * Stage a modify-order operation for the given UTA.
   *
   * `params.changes_json` is a JSON-serialized changes object.
   */
  stageModifyOrder(utaId: string, params: StageModifyOrderParams): Promise<AddResultNapi>
  /**
   * Stage a close-position operation for the given UTA.
   *
   * `params.contract_json` is a JSON-serialized contract object.
   * `params.quantity` is an optional decimal string for partial closes.
   */
  stageClosePosition(utaId: string, params: StageClosePositionParams): Promise<AddResultNapi>
  /**
   * Prepare a commit for the given UTA.
   *
   * Transitions the staging area into a pending commit with the given
   * message. Does not execute any broker calls — call `push` for that.
   */
  commit(utaId: string, message: string): Promise<CommitPrepareResultNapi>
  /**
   * Execute the pending commit for the given UTA against the broker.
   *
   * On success, returns a `PushResultNapi` with the commit hash and
   * per-operation results split into `submitted` and `rejected` lists.
   * On broker failure, returns a `BROKER_ERROR:{json}` napi error.
   */
  push(utaId: string): Promise<PushResultNapi>
  /**
   * Reject the pending commit for the given UTA.
   *
   * Records a `[rejected]` commit in the git log without invoking the broker.
   * `reason` is appended to the commit message.
   */
  reject(utaId: string, reason: string): Promise<RejectResultNapi>
  /**
   * Sync external order-status updates into the git log for the given UTA.
   *
   * `updates` is a list of order status changes. `current_state_json` is a
   * JSON-serialized `GitState` snapshot from the broker.
   */
  sync(utaId: string, updates: Array<OrderStatusUpdateNapi>, currentStateJson: string): Promise<SyncResultNapi>
  /**
   * Export the full git state for the given UTA.
   *
   * Returns the commit log and HEAD hash as JSON strings (safe for napi
   * boundary; TS parses from JSON).
   */
  exportState(utaId: string): Promise<GitExportStateNapi>
  /** Get the current broker health info for the given UTA. */
  getHealth(utaId: string): Promise<BrokerHealthInfoNapi>
  /**
   * Nudge the recovery task for the given UTA to retry from attempt 0.
   *
   * Fire-and-forget — returns immediately. Useful when the operator knows
   * the broker is back online and wants to skip the backoff window.
   */
  nudgeRecovery(utaId: string): Promise<void>
  /**
   * Return the account snapshot from the latest commit's `state_after`.
   *
   * Derives from `export_state()` — no UtaCommand extension needed.
   * If there are no commits yet, all fields are "0".
   */
  getAccount(utaId: string): Promise<AccountSnapshotNapi>
  /**
   * Return positions from the latest commit's `state_after.positions`.
   *
   * Derives from `export_state()` — no UtaCommand extension needed.
   * Each position is serialized to an opaque JSON string (broker-shape passthrough).
   * Returns an empty list if there are no commits yet.
   */
  getPositions(utaId: string): Promise<Array<PositionSnapshotNapi>>
  /**
   * Build a `TradingCore` from config. Call once at app startup.
   *
   * `tokio::runtime::Handle::current()` at this point captures Node's
   * embedded tokio runtime via the `napi-rs tokio_rt` feature.
   */
  static create(config: TradingCoreConfig): Promise<TradingCore>
  /**
   * Spawn and register a UTA actor for the given account config.
   *
   * Wires `UtaState.event_tx` so that the actor can emit `UtaEvent`s;
   * those events are mapped to `TradingCoreEvent` and forwarded through
   * the `EventDispatcher` (ring buffer + mpsc). A background task drains
   * the mpsc and calls the registered `ThreadsafeFunction` (if any).
   *
   * Returns an error if a UTA with the same `id` is already initialized;
   * call `shutdown_uta` first.
   */
  initUta(accountConfig: AccountConfig): Promise<void>
  /**
   * Shut down the UTA actor for the given account.
   *
   * Removes the proxy handle from the registry (dropping the mpsc sender,
   * which will cause the forward task to finish naturally). The actor
   * receives a Shutdown command and terminates cleanly. Both the actor
   * and forwarder tasks are aborted.
   */
  shutdownUta(utaId: string): Promise<void>
  /**
   * Register a TypeScript callback to receive events for the given UTA.
   *
   * Uses `napi-rs` `ThreadsafeFunction` so the callback is invoked on the
   * JS thread without blocking the Tokio runtime. Only one callback per UTA
   * is kept; calling again replaces the previous one.
   */
  subscribeEvents(uta_id: string, callback: (err: Error | null, event: TradingCoreEvent) => void): void
  /**
   * Return all ring-buffered events for `uta_id` with seq > `after_seq`.
   *
   * Used by the TS `RustUtaProxy._backfill()` method when a gap in the
   * event stream is detected (`event.seq !== lastSeq + 1`).
   */
  eventLogRecent(utaId: string, afterSeq: number): Array<TradingCoreEvent>
}
export declare class TradingGit {
  /** Create a new TradingGit with default stub config (hash_version=2). */
  static create(): TradingGit
  /** Restore from a previously exported state JSON string. */
  static restore(stateJson: string): TradingGit
  /**
   * Stage an operation. operation_json is JSON of the Operation (serde_json
   * tagged enum). Returns JSON of AddResult.
   */
  add(operationJson: string): string
  /** Prepare a commit. Returns JSON of CommitPrepareResult. */
  commit(message: string): string
  /**
   * Execute staged operations.
   *
   * stub_results_json: optional JSON array of OperationResult to use as
   * scripted responses. When provided, they are loaded into the shared
   * buffer and consumed in order by the execute_operation closure.
   * An empty array (or None) causes the closure to use a default stub.
   *
   * Returns JSON of PushResult.
   */
  push(stubResultsJson?: string | undefined | null): string
  /** Reject the pending commit. Returns JSON of RejectResult. */
  reject(reason?: string | undefined | null): string
  /** Export the current state as JSON string (GitExportState). */
  exportState(): string
  /** Show a commit by hash. Returns JSON of GitCommit or null. */
  show(hash: string): string | null
  /** Get current status as JSON string (GitStatus). */
  status(): string
  /** Get canonical JSON of the export state (pretty=true matches TS canonicalJson). */
  canonicalExportState(): string
}
